DROP DATABASE IF EXISTS burgers_db;

CREATE DATABASE burgers_db;

USE burgers_db;


CREATE TABLE IF NOT EXISTS burgers (
	id INTEGER(10) UNSIGNED AUTO_INCREMENT NOT NULL
    , burger_name VARCHAR(100) NOT NULL
    , devoured BOOLEAN DEFAULT FALSE
    , dateTimeUpdated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    , PRIMARY KEY(id)
);